prodaction:
  adapter: postgresql
  encoding: unicode
  database: testapp
  username: dpoint
  password: "qwe123"
  pool: 50

development:
  adapter: postgresql
  encoding: unicode
  database: testapp
  username: dpoint
  password: "qwe123"
  pool: 50

test:
  adapter: postgresql
  encoding: unicode
  database: testapp_test
  username: dpoint
  password: "qwe123"
  pool: 5